name: Simple Workflow

on: workflow_dispatch
  # $SELECTION_PLACEHOLDER$
  #   push:
  #     branches:
  #       - main
jobs:
  single-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: |
        echo "Hello, World!"
        echo " Ram One tera byte"
        echo "Memory one Zeta byte"
