name: First Work flow

on: workflow_dispatch
  # $SELECTION_PLACEHOLDER$
  #   push:
  #     branches:
  #       - main
jobs:
  single-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
